[plugins]
# Paperweight
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
hangar = { id = "io.papermc.hangar-publish-plugin", version.ref = "hangar" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[versions]
# Paper API
paper = "1.21.4-R0.1-SNAPSHOT"
velocity = "3.3.0-SNAPSHOT"
minecraft = "1.21.4"
brigadier = "1.3.10"

# Gradle Plugins
paperweight = "2.0.0-beta.10"
runPaper = "2.3.1"
minotaur = "2.8.7"
hangar = "0.1.2"
shadow = "9.0.0-beta4"

# Plugins
decentholograms = "2.8.8"
headdatabaseapi = "1.3.1"
placeholderapi = "2.11.6"
fancyholograms = "2.3.3"
oraxen = "1.171.0"

# Fusion API
fusion = "1.0.1"

# Common API
jetbrains = "24.1.0"
adventure = "4.17.0"

[libraries]
# Velocity API
velocity = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }

# Mojang API
brigadier = { module = "com.mojang:brigadier", version.ref = "brigadier" }

# Paper API
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

# Kyori API
kyori-logger = { module = "net.kyori:adventure-text-logger-slf4j", version.ref = "adventure" }
kyori-text = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
kyori-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }

# Bukkit Plugins API
decent-holograms = { module = "com.github.decentsoftware-eu:decentholograms", version.ref = "decentholograms" }
headdatabaseapi = { module = "com.arcaniax:HeadDatabase-API", version.ref = "headdatabaseapi" }
fancy-holograms = { module = "de.oliver:FancyHolograms", version.ref = "fancyholograms" }
placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }
oraxen = { module = "io.th0rgal:oraxen", version.ref = "oraxen" }
cmi-api = { module = "CMI-API:CMI-API", version = "9.7.4.1" }
cmi-lib = { module = "CMILib:CMILib", version = "1.5.1.4" }

# Plugins
pl3xmap = { group = "maven.modrinth", name = "pl3xmap", version = "1.21-507" }

# Fusion Core API
fusion-paper = { module = "com.ryderbelserion.fusion:fusion-paper", version.ref = "fusion" }
fusion-core = { module = "com.ryderbelserion.fusion:fusion-core", version.ref = "fusion" }

jetbrains = { module = "org.jetbrains:annotations", version.ref = "jetbrains" }

[bundles]
# Soft Depends
dependencies = ["decent-holograms", "fancy-holograms", "cmi-lib", "cmi-api"]

# Shared with the git submodules
shared = ["headdatabaseapi", "placeholderapi", "oraxen"]

# Adventure API
adventure = ["kyori-api", "kyori-text", "kyori-logger"]