name: '${name}'
main: '${group}.Pl3xMapExtras'

version: '${version}'
api-version: '${minecraft}'
description: '${description}'

dependencies:
  server:
    Pl3xMap:
      load: BEFORE
      required: true
      join-classpath: true
    Essentials:
      load: BEFORE
      required: false
      join-classpath: true
    PlayerWarps:
      load: BEFORE
      required: false
      join-classpath: true
    ClaimChunk:
      load: BEFORE
      required: false
      join-classpath: true
    GriefDefender:
      load: BEFORE
      required: false
      join-classpath: true
    GriefPrevention:
      load: BEFORE
      required: false
      join-classpath: true
    PlotSquared:
      load: BEFORE
      required: false
      join-classpath: true
    WorldGuard:
      load: BEFORE
      required: false
      join-classpath: true
    HeadDatabase:
      load: BEFORE
      required: false
      join-classpath: true